// Generated by manually running Rcpp::compileAttributes()
// Do not edit by hand
#ifndef RCPP_hrfals_RCPPEXPORTS_H
#define RCPP_hrfals_RCPPEXPORTS_H

#include <RcppArmadillo.h>
#include <Rcpp.h>

arma::mat lss_kernel_cpp(const arma::mat& C, const arma::mat& A, const arma::mat& Y, double lambda_ridge = 0.0, bool shared_C = true);

#endif
