// Generated by manually running Rcpp::compileAttributes()
// Do not edit by hand
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lss_kernel_cpp
arma::mat lss_kernel_cpp(const arma::mat& C, const arma::mat& A, const arma::mat& Y, double lambda_ridge = 0.0, bool shared_C = true);

RcppExport SEXP _hrfals_lss_kernel_cpp(SEXP CSEXP, SEXP ASEXP, SEXP YSEXP, SEXP lambda_ridgeSEXP, SEXP shared_CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_ridge(lambda_ridgeSEXP);
    Rcpp::traits::input_parameter< bool >::type shared_C(shared_CSEXP);
    rcpp_result_gen = Rcpp::wrap(lss_kernel_cpp(C, A, Y, lambda_ridge, shared_C));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hrfals_lss_kernel_cpp", (DL_FUNC) &_hrfals_lss_kernel_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hrfals(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
