# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Enhanced LSS kernel implemented in C++ with optimizations
#'
#' This implementation provides multiple solver strategies, enhanced numerical
#' stability, and optimized memory access patterns for improved performance.
#'
#' @param C Matrix of trial regressors (n x T)
#' @param A Matrix of nuisance regressors (n x m)
#' @param Y BOLD data matrix (n x V)
#' @param p_vec Vector of length n for LSS algorithm (see FastLSS proposal)
#' @param lambda_ridge Ridge penalty applied when computing (A^T A)
#' @param shared_C Logical flag for future extensions (currently ignored)
#' @param eig_tol Tolerance for eigenvalue checks (default: adaptive)
#' @param denom_tol Tolerance for denominator checks (default: 1e-10)
#' @param block_size Block size for voxel processing (default: 1000)
#' @return Matrix of trial coefficients (T x V)
#' @export
lss_kernel_cpp <- function(C, A, Y, p_vec, lambda_ridge = 0.0, shared_C = TRUE, eig_tol = -1.0, denom_tol = 1e-10, block_size = 1000L) {
    .Call(`_hrfals_lss_kernel_cpp`, C, A, Y, p_vec, lambda_ridge, shared_C, eig_tol, denom_tol, block_size)
}

#' Diagnostic function to check matrix conditioning
#'
#' @param A Nuisance regressor matrix
#' @param lambda_ridge Ridge penalty
#' @return List with condition number and other diagnostics
#' @export
lss_check_conditioning <- function(A, lambda_ridge = 0.0) {
    .Call(`_hrfals_lss_check_conditioning`, A, lambda_ridge)
}

