# Generated by manually running Rcpp::compileAttributes()
# Do not edit by hand

lss_kernel_cpp <- function(C, A, Y, lambda_ridge = 0, shared_C = TRUE) {
    .Call(`_hrfals_lss_kernel_cpp`, C, A, Y, lambda_ridge, shared_C)
}
